## Importing the necessary libraries and packages

In [1]:
import keras
import PIL
import h5py
import numpy as np
from keras import optimizers
from keras.models import Sequential
from keras.layers import Conv2D,MaxPooling2D
from keras.layers import Activation,Dropout,Flatten,Dense
from keras.preprocessing.image import array_to_img, img_to_array, load_img
from keras.preprocessing.image import ImageDataGenerator 
from keras import applications
from keras import Model

c:\anaconda3\envs\tensorflow\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


## Convnet Team Impasta
### 15 layer cnn

In [188]:
model = Sequential()

## 3D feature maps section
model.add(Conv2D(32, (3, 3), input_shape=(150, 150,3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(32, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

# 1D flattened section
model.add(Flatten())
model.add(Dense(64))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(1))
model.add(Activation('sigmoid'))

In [189]:
# Defining model characteristics
model.compile(loss='binary_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

In [169]:
batch_size = 16 ## Feel free to change , a batch_size of 5 provides whole number of training and testing samples

# Modifying the training dataset with minor augmentations . This technique is done to overcome the large sample cost
datagen_train = ImageDataGenerator(rescale=1./255,zoom_range=0.2,shear_range=0.2,horizontal_flip=True)
#only augmentation used for testing/validation , because training is already done,only a normalization is required
datagen_test = ImageDataGenerator(rescale=1./255)

#generator function to read traniing input data
# class_mode is set to binary , because we have 2 classes , pasta and impasta
# all images are converted to 150x150x3 format
train_generator = datagen_train.flow_from_directory(
        'c:/input/train',target_size=(150, 150),batch_size=batch_size,class_mode='binary')


#generator function to read test input data
validation_generator =datagen_test.flow_from_directory(
        'c:/input/validation',target_size=(150, 150),batch_size=batch_size,class_mode='binary')

Found 1855 images belonging to 2 classes.
Found 320 images belonging to 2 classes.


In [170]:
#Fitting the model using our train and validation generators , we will use this model to run it on our test images
model.fit_generator(
        train_generator,steps_per_epoch=1855 // batch_size,epochs=50,validation_data=validation_generator,
        validation_steps=320 // batch_size)

model.save_weights('our_model.h5')  # always save your weights after training or during training

Epoch 1/50
115/115 [==============================] - 24s 210ms/step - loss: 0.7322 - acc: 0.5062 - val_loss: 0.6891 - val_acc: 0.5062
Epoch 2/50
115/115 [==============================] - 24s 207ms/step - loss: 0.6994 - acc: 0.5562 - val_loss: 0.6765 - val_acc: 0.5594
Epoch 3/50
115/115 [==============================] - 24s 206ms/step - loss: 0.6851 - acc: 0.5823 - val_loss: 0.6567 - val_acc: 0.5781
Epoch 4/50
115/115 [==============================] - 24s 205ms/step - loss: 0.6735 - acc: 0.6052 - val_loss: 0.6302 - val_acc: 0.6312
Epoch 5/50
115/115 [==============================] - 24s 210ms/step - loss: 0.6682 - acc: 0.5987 - val_loss: 0.6298 - val_acc: 0.6594
Epoch 6/50
115/115 [==============================] - 23s 204ms/step - loss: 0.6522 - acc: 0.6179 - val_loss: 0.6166 - val_acc: 0.6687
Epoch 7/50
115/115 [==============================] - 23s 199ms/step - loss: 0.6601 - acc: 0.6182 - val_loss: 0.6099 - val_acc: 0.6344
Epoch 8/50
115/115 [==============================] - 2

## Prediction on Test Data

In [190]:
model.load_weights('our_model.h5')

In [191]:
datagen_test = ImageDataGenerator(rescale=1./255)
test_generator_pasta =datagen_test.flow_from_directory(
        'c:/input/test',target_size=(150, 150),batch_size=batch_size,
    class_mode='binary',shuffle=False)

output=np.round(model.predict_generator(test_generator_pasta))
print(output)

Found 160 images belonging to 2 classes.
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]

In [192]:
output_scores=(model.predict_generator(test_generator_pasta))
print(output_scores)

[[7.06057250e-01]
 [1.85568437e-01]
 [6.43836483e-02]
 [2.42230475e-01]
 [3.52466434e-01]
 [1.03752531e-01]
 [6.45850673e-02]
 [6.01263106e-01]
 [7.97420368e-03]
 [9.37162578e-01]
 [3.87977391e-01]
 [4.12280619e-01]
 [2.08904445e-01]
 [6.28224984e-02]
 [6.03662193e-01]
 [1.40219675e-02]
 [6.87914550e-01]
 [8.03529397e-02]
 [1.64796913e-03]
 [4.23646629e-01]
 [1.69542320e-02]
 [4.35916036e-01]
 [7.50421123e-07]
 [3.08826327e-01]
 [3.71228973e-03]
 [5.48562050e-01]
 [2.49806136e-01]
 [1.89871684e-01]
 [5.95745519e-02]
 [1.76799744e-01]
 [2.10506911e-03]
 [7.62459561e-02]
 [5.31594753e-01]
 [2.93098912e-02]
 [3.55595052e-01]
 [1.03502974e-01]
 [4.14005555e-02]
 [1.12320885e-01]
 [4.44742948e-01]
 [1.45668332e-02]
 [7.09690332e-01]
 [4.29027043e-02]
 [1.10223051e-03]
 [6.08925940e-03]
 [3.89422238e-01]
 [1.95040017e-01]
 [8.02453458e-01]
 [8.33931491e-02]
 [3.44621709e-09]
 [8.96868855e-02]
 [3.19760680e-01]
 [1.45107672e-01]
 [3.95632838e-07]
 [8.77506018e-01]
 [1.84159368e-01]
 [1.144544

# VGG

## Using pretrained VGG

In [3]:
## Using pretrained features for conv layers and running a new fully connected training over it

In [139]:
#using vgg16 from applciations pkg
model =applications.VGG16(include_top=False, weights='imagenet')

# batch_size set of 5( Both to force individulaity and to be divisible by the dataset total)
batch_size =5

## creating data generators for our images
datagen =ImageDataGenerator(rescale=1. / 255)
generator= datagen.flow_from_directory(
        'c:/input/train',
        target_size=(150, 150),shuffle=False,
        batch_size=batch_size,class_mode=None)

## gathering the images run through the vgg to save it to use the info
## later to input it into our own fully connected

## these features are called bottleneck features , as they restrict the efficiency
## as these are trained already , but in this case the images are from imagenet itself.
train_bottleneckfeatures =model.predict_generator(generator, 1855//batch_size)
# 1855 is the number of training images

# creating a numpy array and saving it as a npy file for use later
np.save(open('bottleneck_features_train.npy', 'wb'), train_bottleneckfeatures)

## doing the same setup for valdiation data
generator =datagen.flow_from_directory(
        'c:/input/validation',target_size=(150, 150),
        batch_size=batch_size,class_mode=None,shuffle=False)
validation.bottleneckfeatures = model.predict_generator(generator, 320//batch_size)
# also , 320 is the number of validation data
np.save(open('bottleneck_features_validation.npy', 'wb'), validation_bottleneckfeatures)

Found 1855 images belonging to 2 classes.
Found 320 images belonging to 2 classes.


In [141]:
## reading the data from default vgg and using it as input for our modification over it
train_data =np.load(open('bottleneck_features_train.npy', 'rb'))
train_labels =np.array([0] * 880 + [1] * 975)
validation_data =np.load(open('bottleneck_features_validation.npy', 'rb'))
validation_labels =np.array([0] * 160 + [1] * 160)

## adding modification over vgg and fitting it with a sigmoid to obtain binary classification
model =Sequential()
model.add(Flatten(input_shape=train_data.shape[1:])) # interface the vgg to our fully connected layers using the output from npy file 
model.add(Dense(256, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(1, activation='sigmoid'))

In [10]:
model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['accuracy'])

# fitting the fully connected
model.fit(train_data, train_labels,epochs=50,batch_size=batch_size,
          validation_data=(validation_data, validation_labels))

## saving the model weights for future use
model.save_weights('bottleneck_fc_model.h5')

Train on 1855 samples, validate on 320 samples
Epoch 1/50
1855/1855 [==============================] - 4s 2ms/step - loss: 0.8435 - acc: 0.6388 - val_loss: 0.5405 - val_acc: 0.7281
Epoch 2/50
1855/1855 [==============================] - 3s 2ms/step - loss: 0.6066 - acc: 0.7148 - val_loss: 0.7514 - val_acc: 0.6938
Epoch 3/50
1855/1855 [==============================] - 3s 2ms/step - loss: 0.5620 - acc: 0.7504 - val_loss: 0.5105 - val_acc: 0.7469
Epoch 4/50
1855/1855 [==============================] - 3s 2ms/step - loss: 0.5163 - acc: 0.7704 - val_loss: 0.4256 - val_acc: 0.7875
Epoch 5/50
1855/1855 [==============================] - 3s 2ms/step - loss: 0.4984 - acc: 0.7849 - val_loss: 0.3551 - val_acc: 0.8500
Epoch 6/50
1855/1855 [==============================] - 3s 2ms/step - loss: 0.4545 - acc: 0.8135 - val_loss: 0.3285 - val_acc: 0.8500
Epoch 7/50
1855/1855 [==============================] - 3s 2ms/step - loss: 0.4336 - acc: 0.8183 - val_loss: 0.3070 - val_acc: 0.8406
Epoch 8/50
1855

## Finetuning top layers

In [173]:
##Fine tuning top layers

## Transfer Learning
# We are now retraining the final convolution layer set of the convnet with specific input images

In [180]:
weights_path = 'vgg16_weights.h5'

In [181]:
batch_size = 5

# build the VGG16 network
base_model = applications.VGG16(weights='imagenet',include_top=False,input_shape = (150,150,3))

# replicate the fully connected layers from previous model
top_model =Sequential()
top_model.add(Flatten(input_shape=base_model.output_shape[1:]))
top_model.add(Dense(256, activation='relu'))
top_model.add(Dropout(0.5))
top_model.add(Dense(1, activation='sigmoid'))

## Architecture Idea
## base VGG , first 15 layers +
## Conv layers (transfer learning)+
## fully connected layer(transfer learning)


In [182]:
top_model_weights_path ='bottleneck_fc_model.h5' ## to be put in the same folder or give complete path
top_model.load_weights(top_model_weights_path)

#combine the top model and base model
model=Model(inputs= base_model.input, outputs= top_model(base_model.output))

#we set the first 15 layers to retain weights , we train the rest of the model with our data
for layer in model.layers[:15]:
    layer.trainable = False
    
# now train the top layers again to fit the problem statement more 
model.compile(loss='binary_crossentropy',
              optimizer=optimizers.SGD(lr=1e-4, momentum=0.9),
              metrics=['accuracy'])

In [58]:
batch_size = 5

# Modifying the training dataset with minor augmentations.
train_datagen = ImageDataGenerator(rescale=1./255,
        shear_range=0.2,zoom_range=0.2,
        horizontal_flip=True)

test_datagen=ImageDataGenerator(rescale=1./255)

train_generator =train_datagen.flow_from_directory('c:/input/train',
        target_size=(150, 150),batch_size=batch_size,
        class_mode='binary')

validation_generator = test_datagen.flow_from_directory('c:/input/validation',
        target_size=(150, 150),batch_size=batch_size,
        class_mode='binary')

# finetuning the model
model.fit_generator(
        train_generator,
        steps_per_epoch=1855 // batch_size,
        epochs=50,
        validation_data=validation_generator,
        validation_steps=320 // batch_size)

Found 1855 images belonging to 2 classes.
Found 320 images belonging to 2 classes.
Epoch 1/50
371/371 [==============================] - 29s 77ms/step - loss: 0.6430 - acc: 0.6491 - val_loss: 0.5794 - val_acc: 0.7125
Epoch 2/50
371/371 [==============================] - 28s 75ms/step - loss: 0.6344 - acc: 0.6744 - val_loss: 0.5533 - val_acc: 0.7438
Epoch 3/50
371/371 [==============================] - 28s 75ms/step - loss: 0.6128 - acc: 0.6922 - val_loss: 0.5691 - val_acc: 0.7344
Epoch 4/50
371/371 [==============================] - 28s 75ms/step - loss: 0.5861 - acc: 0.7127 - val_loss: 0.5254 - val_acc: 0.7656
Epoch 5/50
371/371 [==============================] - 28s 76ms/step - loss: 0.5452 - acc: 0.7375 - val_loss: 0.5034 - val_acc: 0.7563
Epoch 6/50
371/371 [==============================] - 28s 75ms/step - loss: 0.5559 - acc: 0.7342 - val_loss: 0.5018 - val_acc: 0.7781
Epoch 7/50
371/371 [==============================] - 28s 76ms/step - loss: 0.5244 - acc: 0.7660 - val_loss: 0.45

In [59]:
# saving the weights
model.save_weights('finetuned.h5')

In [183]:
## giving the summary of the Fine-Tuned VGG architecture
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_24 (InputLayer)        (None, 150, 150, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 150, 150, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 150, 150, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 75, 75, 64)        0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 75, 75, 128)       73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 75, 75, 128)       147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 37, 37, 128)       0         
__________

In [184]:
## Prediction for test images

model.load_weights('finetuned.h5')
test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
        'c:/input/test',
        target_size=(150, 150),
        batch_size=batch_size,
        class_mode='binary',
        shuffle=False)

Found 160 images belonging to 2 classes.


In [185]:
output_finetune=np.round(model.predict_generator(
        test_generator,
        steps=None))

In [186]:
print(output_finetune)

[[0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]]


In [187]:
output_finescore=(model.predict_generator(
        test_generator,
        steps=None))
print(output_finescore)

[[2.37390668e-36]
 [7.26114035e-01]
 [9.96921957e-01]
 [4.40766526e-05]
 [7.11116854e-07]
 [9.89976765e-22]
 [6.41088382e-09]
 [3.23921588e-04]
 [9.04609077e-03]
 [6.25374675e-01]
 [3.91732341e-10]
 [9.96817052e-01]
 [1.31895911e-10]
 [3.06205481e-01]
 [9.14807975e-01]
 [6.15677399e-33]
 [2.06418753e-01]
 [4.43626307e-02]
 [8.26309612e-26]
 [4.60173624e-08]
 [7.13441405e-04]
 [2.29475634e-24]
 [5.64501097e-05]
 [2.00619985e-17]
 [8.00125301e-01]
 [8.29863489e-01]
 [3.82300501e-13]
 [1.84570354e-06]
 [9.75841999e-01]
 [2.97980709e-03]
 [1.09200031e-04]
 [2.36251130e-09]
 [9.29680599e-16]
 [3.58616337e-02]
 [1.91538945e-01]
 [1.12304169e-05]
 [7.75052488e-01]
 [1.63725895e-14]
 [1.90603808e-01]
 [6.79215640e-02]
 [1.28233477e-01]
 [4.84985912e-06]
 [1.38775402e-04]
 [0.00000000e+00]
 [7.53765285e-01]
 [1.24562018e-06]
 [5.33908665e-01]
 [1.51367989e-14]
 [2.85203714e-06]
 [8.32814097e-01]
 [2.21939786e-06]
 [9.80398618e-04]
 [1.65396938e-29]
 [5.71111366e-02]
 [9.77555260e-07]
 [3.354226